### ISSUE TITLE
CBERS bucket to become a `Requester Pays bucket`

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/cbers-tiler#1]
Next Saturday, `cbers-pds` is going to be set as `requester pays` bucket, meaning application will have to be deployed in `us-east-1` region to be able to access CBERS-4 data freely. 

On the GDAL/Rasterio side, I think we will need to set `AWS_REQUEST_PAYER` environment variable like for `sentinel2-s2-l2a` pds:

```
AWS_REQUEST_PAYER='requester' rio info s3://sentinel-s2-l2a/tiles/38/S/NG/2017/10/9/1/R10m/B02.jp2
```

**Comment by fredliporace** [comment]
Requester pays enabled some minutes ago.

**Comment by vincentsarago** [comment]
thanks @fredliporace 🙏
